import type { AprovacaoData } from '../types/aprovacao'

export const dassgMes1: AprovacaoData = {
  slug: 'dassg-mes1',
  cliente: 'Dassg Têmpera',
  eyebrow: 'Dassg Têmpera · Redes sociais',
  titulo: 'Aprovação',
  tituloDestaque: 'Mês 01',
  intro: 'Quatro posts prontos pro primeiro mês. Abre a legenda completa de cada um e deixa um comentário embaixo caso queira algum ajuste.',
  validadeTexto: 'quinta-feira, pra manter a publicação no calendário do mês',
  estrategia: [
    {
      numero: '01',
      titulo: 'Lançamento',
      texto: 'Apresenta a marca pelo que ela já entrega (escala, tempo de mercado), sem precisar convencer de nada',
    },
    {
      numero: '02',
      titulo: 'Educar',
      texto: 'Explica o processo pra quem nunca ouviu falar, constrói autoridade técnica antes de vender',
    },
    {
      numero: '03',
      titulo: 'Mostrar',
      texto: 'Abre a estrutura por trás da operação, transforma escala em confiança',
    },
    {
      numero: '04',
      titulo: 'Posicionar',
      texto: 'Reforça o diferencial competitivo frente à concorrência',
    },
  ],
  posts: [
    {
      numero: '01',
      titulo: 'Lançamento',
      pilar: 'Semana 1',
      imagem: '/img/aprovacoes/dassg-mes1/semana-1.jpg',
      handle: 'dassg_tempera',
      legendaPreview: '800 toneladas de aço por mês passam pelos nossos fornos...',
      descricaoAprovacao: 'Apresenta a Dassg Têmpera pelo que ela já entrega: mais de 20 anos de operação e 800 toneladas de aço tratadas por mês. Primeiro contato reforça escala e experiência, sem precisar convencer de nada.',
      legendaCorpo: [
        '800 toneladas de aço por mês passam pelos nossos fornos, todo mês, há mais de 20 anos.',
        'Somos a DASSG TÊMPERA: especialistas em tratamento térmico para as indústrias automotiva, metalmecânica, agrícola e de bens de capital, com processos rastreáveis, certificação ISO 9001 e infraestrutura de alta tecnologia em Araquari, SC.',
        'Nosso propósito vai além do forno: transformar a estrutura dos metais para gerar valor para as pessoas, para a indústria e para o futuro.',
        'Acompanhe nosso perfil e veja conteúdo técnico, bastidores e novidades do setor.',
      ],
      hashtags: '#TratamentoTérmico #Têmpera #IndústriaMetalmecânica #ISO9001 #SantaCatarina #Araquari #Joinville #DassgTêmpera',
      publicarQuando: 'semana 1',
      plataformas: ['Instagram', 'Facebook', 'LinkedIn'],
    },
    {
      numero: '02',
      titulo: 'O que é a têmpera',
      pilar: 'Semana 2 · Educar',
      imagem: '/img/aprovacoes/dassg-mes1/semana-2.jpg',
      handle: 'dassg_tempera',
      legendaPreview: 'Você sabe o que acontece quando um metal passa pela têmpera?',
      descricaoAprovacao: 'Explica o que é a têmpera pra quem nunca ouviu falar, do jeito mais simples possível: o que muda na estrutura do aço e os 3 ganhos reais disso (mais dureza, mais resistência mecânica, vida útil maior).',
      legendaCorpo: [
        'Você sabe o que acontece quando um metal passa pela têmpera?',
        'A têmpera é um dos processos mais importantes do tratamento térmico. A peça é aquecida a temperaturas altíssimas e resfriada bruscamente. É essa mudança rápida que transforma a estrutura do aço e entrega maior dureza, mais resistência mecânica e vida útil muito maior.',
        'Na DASSG TÊMPERA, cada peça é tratada com controle preciso de temperatura, atmosfera e tempo de processo, tudo documentado e rastreável.',
        'Quer saber qual tratamento térmico é ideal para a sua aplicação? Fale com a gente.',
      ],
      hashtags: '#Têmpera #TratamentoTérmico #AçoIndustrial #EngenhariaMetalúrgica #IndústriaMetalmecânica #DassgTêmpera #SantaCatarina',
      publicarQuando: 'semana 2',
      plataformas: ['Instagram', 'Facebook', 'LinkedIn'],
    },
    {
      numero: '03',
      titulo: 'A estrutura da Dassg',
      pilar: 'Semana 3 · Mostrar',
      imagem: '/img/aprovacoes/dassg-mes1/semana-3.jpg',
      handle: 'dassg_tempera',
      legendaPreview: 'A estrutura da DASSG TÊMPERA: onde a transformação acontece.',
      descricaoAprovacao: 'Mostra a estrutura por trás da operação em Araquari: fornos de alta e baixa temperatura, certificação ISO 9001, energia solar e a equipe que conhece cada detalhe do processo.',
      legendaCorpo: [
        'A estrutura da DASSG TÊMPERA: onde a transformação acontece.',
        'Nossos fornos de alta e baixa temperatura trabalham com precisão para garantir que cada peça saia com as propriedades mecânicas exatas que o seu processo exige.',
        'Araquari, SC, na região metropolitana de Joinville. Certificação ISO 9001, operação com energia solar e uma equipe que conhece cada forno e cada detalhe.',
      ],
      hashtags: '#BastidoresIndustriais #FornosIndustriais #TratamentoTérmico #ISO9001 #DassgTêmpera #IndústriaMetalmecânica #SantaCatarina',
      publicarQuando: 'semana 3',
      plataformas: ['Instagram', 'Facebook', 'LinkedIn'],
    },
    {
      numero: '04',
      titulo: 'Agilidade e pontualidade',
      pilar: 'Semana 4 · Posicionar',
      imagem: '/img/aprovacoes/dassg-mes1/semana-4.jpg',
      handle: 'dassg_tempera',
      legendaPreview: 'Prazo perdido custa caro pra quem depende da sua peça...',
      descricaoAprovacao: 'Reforça o diferencial competitivo: transporte próprio significa menos dependência de terceiro e mais previsibilidade de prazo pra quem depende da peça.',
      legendaCorpo: [
        'Prazo perdido custa caro pra quem depende da sua peça pra seguir a linha de produção.',
        'Por isso a DASSG TÊMPERA opera com transporte próprio: sem depender de terceiro pra cumprir prazo, sem ficar refém do horário de outra transportadora. Agilidade e pontualidade não são promessa, são estrutura.',
        'Rastreabilidade, qualidade certificada e logística própria: assim que uma peça sai daqui, ela chega no seu prazo.',
      ],
      hashtags: '#Logística #TransportePróprio #Agilidade #Pontualidade #TratamentoTérmico #IndústriaMetalmecânica #DassgTêmpera #SantaCatarina',
      publicarQuando: 'semana 4',
      plataformas: ['Instagram', 'Facebook', 'LinkedIn'],
    },
  ],
  contato: {
    whatsapp: '5547992358161',
  },
}
